name: flutter_html
description: A Flutter widget for rendering static HTML and CSS as Flutter widgets.
version: 3.0.0-beta.2
homepage: https://github.com/Sub6Resources/flutter_html #original
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  # Plugin for parsing html
  html: ^0.15.4

  # Plugin for parsing css
  csslib: ^0.17.2

  # Plugin for firstWhereOrNull extension on lists
  collection: ^1.17.0

  # plugin to manage lists and counting in a variety of styles
  list_counter: ^1.0.2

  flutter_tools:
    path: ../flutter_tools

  tree_traversal:
    git: #todo replace with package
      url: git@github.com:mcmah309/tree_traversal.git
      ref: main

  rust: ^3.0.0
  rewind: ^0.3.5
  meta: ^1.8.0

  flutter:
    sdk: flutter

# dependency_overrides:
#   rust: 3.0.0-dev.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  melos: ^3.0.1


screenshots:
  - description: 'An example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot.png
  - description: 'Continued example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot1.png
  - description: 'Continued example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot2.png
  - description: 'Continued example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_screenshot3.png
  - description: 'Another example of the output produced by flutter_html'
    path: example/screenshots/flutter_html_readme_screenshot.png

funding:
  - https://opencollective.com/flutter_html

topics:
  - html
  - css
  - widgets
  - layout
